### ISSUE TITLE
TypeError: prepare_model_for_int8_training() got an unexpected keyword argument  'output_embedding_layer_name' in run_rlhf_train.py

### ISSUE THREAD

**Issue by ksmin23** [sungeuns/llm-fine-tuning-sagemaker#1]
`run_rlhf_train.py` 파일의 129 라인에서 `prepare_model_for_int8_training()` 함수의 output_embedding_layer_name 파라미터가 최근에 제거 되었습니다.
> pretrained_model = prepare_model_for_int8_training(pretrained_model, output_embedding_layer_name="embed_out")
그래서, SageMaker Training Job이 실패합니다.

CloudWatch의 에러 메시지
> ErrorMessage "TypeError: prepare_model_for_int8_training() got an unexpected keyword argument
 'output_embedding_layer_name'"

**Comment by sungeuns** [comment]
@ksmin23 이 repo의 내용은 이슈 수정해서 [여기](https://github.com/sungeuns/gen-ai-sagemaker/tree/main/Dolly) 로 옮겼습니다, 참고부탁드립니다~
